### ISSUE TITLE
Remove sites that don't link back to the web ring

### ISSUE THREAD

**Issue by teacherbuknoy** [teacherbuknoy/ph-webring#6]
Members of the web ring should link back to other members of the web ring via the `next`, `random`, and `previous` links, as well as the web ring's website. These are the links needed:

- https://webring.antaresph.dev/
- https://webring.antaresph.dev/next
- https://webring.antaresph.dev/random
- https://webring.antaresph.dev/previous

Please include these links on your site. Thanks a lot!

CC: @harudagondi @tedmagaoay

**Comment by harudagondi** [comment]
Hello, I have updated my site to show this on the footer. Would that be fine? https://harudagondi.vercel.app/

**Comment by tedmagaoay** [comment]
just updated

**Comment by teacherbuknoy** [comment]
Thanks for the fast response! This is good. Thank you!
